[package]
name = "spirv-struct-layout-derive"
version = "0.1.0"
authors = ["Tristam MacDonald <tristam@trist.am>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
syn = "1.0"
quote = "1.0"
spirq = "0.0"
